name: Java CI Pipeline

on:
  push:
    branches: [ develop ] # Jalankan saat ada push ke branch develop
  pull_request:
    branches: [ develop ] # Jalankan saat ada Pull Request ke branch develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Gunakan runner Ubuntu terbaru yang disediakan GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action untuk mengambil kode dari repositori

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Action untuk menyiapkan lingkungan Java
        with:
          java-version: '17' # Tentukan versi Java
          distribution: 'temurin' # Tentukan distribusi JDK (Adoptium Temurin adalah pilihan populer)
          cache: maven # Aktifkan caching untuk dependensi Maven

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml # Perintah untuk build dan test menggunakan Maven
        # '-B' atau '--batch-mode' menjalankan Maven dalam mode non-interaktif
        # 'package' akan mengompilasi, menjalankan tes, dan mem-package aplikasi
        # Alternatif: 'mvn -B verify' juga menjalankan pemeriksaan tambahan